#!/bin/bash

sudo add-apt-repository ppa:danielrichter2007/grub-customizer
sudo add-apt-repository ppa:snwh/pulp
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

sudo add-apt-repository ppa:webupd8team/java

sudo apt-get update 

sudo apt-get install grub-customizer

sudo apt-get install paper-gtk-theme paper-icon-theme

sudo apt-get install google-chrome-stable

sudo apt-get install oracle-java8-installer
sudo update-java-alternatives -s java-8-oracle
sudo apt-get install oracle-java8-set-default
